### ISSUE TITLE
ARM support in docker image

### ISSUE THREAD

**Issue by Israphel** [grafana/xk6#98]
hello, is ARM support in the roadmap?

for the record, I built the container with ARM and it worked, the only line I changed was the wget of fixuid to fetch the arm64 binary.

**Comment by gonmmarques** [comment]
I would really also like to know if this is something you would consider.

> hello, is ARM support in the roadmap?
> 
> for the record, I built the container with ARM and it worked, the only line I changed was the wget of fixuid to fetch the arm64 binary.

As I also see that since https://github.com/grafana/xk6/commit/ac390513484c0e716884bb6a0d3d21f53ef460b0, fixuid is compiled instead of fetch as mentioned above by @Israphel. 

@pablochacin is ARM support in your radar at the moment?

Thanks in advance.
